apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      kubernetes:
        service:
          name: backend
      components:
        - name: backend
          image: ghcr.io/bharattech/backend:0.1.0
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - types
        - namespace: wasi
          package: clocks
          interfaces:
            - types
        - namespace: wasi
          package: random
          interfaces:
            - random
        - namespace: wasi
          package: http
          interfaces:
            - client
        - namespace: wasi
          package: http
          interfaces:
            - handler
          config:
            address: '0.0.0.0:8002'