version: 2.4.0
build:
  command: "cargo build --target wasm32-wasip2 --release"
  component_path: "target/wasm32-wasip2/release/middleware.wasm"
  
dev:
  wasip3: true
  address: "0.0.0.0:8001"
  volumes:
    - host_path: ./testdata
      guest_path: /data

workload:
  allowedHosts: [ "*" ]